### ISSUE TITLE
FR8. Login

### ISSUE THREAD

**Issue by srazzaq01** [WSU-4110/JamFynDer#9] opened 2022-09-18 16:34 UTC
|Requirement_ID FR8. Login|
|---|
|**Goal**: Display a login page for the users to log in through their Spotify account
**Stakeholders:** Rafi/users|
| **Description:** When the user enters the web app, they will be presented with the login page. The login page serves as the landing page and will have a prompt for the user to log in through their Spotify account. Furthermore we would like to add a “remember me” option that makes it so that they do not have to enter their login data over and over again. |
| **Origin:** Our initial meeting we suggested that the user needs to log in to save their playlists on to their account |
| **Version:** 1.0|  
|**Date:**  9/18/22  
|  Priority: 2 |

**Comment by Urban-Programmer** [comment] 2022-10-09 06:22
Closing issue, is a duplicate of the Spotify-Sign in page. (We are. only using Spotify API)

**Closed by Urban-Programmer** 2022-10-09 06:22 UTC
Labels: Features, Functional
